### ISSUE TITLE
AttributeError: 'TuyaScanner' object has no attribute 'transport'

### ISSUE THREAD

**Issue by engineerjoe440** [frawau/aiotuya#6]
Just started plugging around with this module since I just recently got a hold of a few Tuya smart plugs and other devices. Ran the simple `python -m aiotuya` and ran into an AttributeError issue. I'm sure that I wouldn't have any issues editing the installed source (I'm pretty familiar with Python). Any thoughts or suggestions?

OS: Windows 10
Python Ver.: 3.7.1
aiohttp: 3.6.2
pycryptodome: 3.9.4

Here is the traceback:
```
$>python -m aiotuya
Hit "Enter" to start
Use Ctrl-C to quit

Traceback (most recent call last):
  File "C:\Users\Molly\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Molly\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Molly\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiotuya\__main__.py", line 240, in <module>
    scanner.close()
  File "C:\Users\Molly\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiotuya\aiotuya.py", line 794, in close
    if self.transport:
AttributeError: 'TuyaScanner' object has no attribute 'transport'
```

**Comment by frawau** [comment]
Hi,

Sorry for the delay in responding.... It was the season.... So Happy New Year.

I have never tried on Windows (I do not use Windows)
. I would not be surprised if I use some function of asyncio that are not 
supported with Windows. 

We ran in that kind of issue when home-assistant wanted to use my aiozeroconf 
library...

Regards,
    François

**Comment by frawau** [comment]
I have no intention on using Windows.... So I close this.
